#management:
# security:
#   enabled: false
# port: 9001

spring:
 application:
   name: microservice-discovery-eureka

server:
 port: 8889
eureka:
 instance:
   hostname: peer2
 client:
    service-url:
     defaultZone: http://user:password123@localhost:8888/eureka/

#---
#spring:
# profiles: peer2
#server:
# port: 8889
#eureka:
# instance:
#   hostname: peer2
# client:
#   service-url:
#    defaultZone: http://localhost:8888/eureka/

