
server:
  port: 8890
banner:
  location: classpath:xml/logo.txt

spring:
 application:
   name: user
# 数据库访问配置
# 主数据源，默认的
 datasource:
   #type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mvctest?useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password:

#management:
# security:
#   enabled: false
# port: 9001

eureka:
 client:
   service-url:
     defaultZone: http://user:password123@localhost:8888/eureka/
#eureka:
# client:
#   register-with-eureka: false
#   fetch-registry: false
#   service-url:
#     defaultZone: http://localhost:${server.port}/eureka/
