management:
 security:
   enabled: false
 port: 9001

spring:
 application:
   name: microservice-discovery-eureka

server:
 port: 8888
eureka:
 instance:
   hostname: peer1
 client:
    service-url:
     defaultZone: http://localhost:8889/eureka/

# 如果不配的话，用户名默认为user 密码为启动时生成的随机数
security:
 basic:
   enabled: true
 user:
  name: user
  password: password123
#---
#spring:
# profiles: peer2
#server:
# port: 8889
#eureka:
# instance:
#   hostname: peer2
# client:
#   service-url:
#    defaultZone: http://localhost:8888/eureka/

